name: test_env

channels:
  - conda-forge
  - xspecmodels
  - defaults
  
dependencies:
  - python
  - mkl
  - numpy
  - pyyaml>=5.1
  - astropy
  - scipy
  - numdifftools
  - hdf5
  - pytables
  - pandas>=0.23
  - dill
  - cfitsio==3.470
  - ccfits
  - wcslib==5.20
  - future
  - xspec-modelsonly==6.25
  - numba>=0.52
  - h5py<3.2
  - interpolation>=2.2.2
  - libgfortran
  - colorama
  - rich
